### ISSUE TITLE
OER encoding issue 1609.3 AddUserService OPTIONALs

### ISSUE THREAD

**Issue by thritter** [certificationoperatingcouncil/TCI_Tools#5]
Checking Link quality and/or Immediate Access yields the same SEQUENCE preamble (Bitfield) 0x04.
Checking Channel Identifier is completly ignored.

**Comment by certificationoperatingcouncil** [comment]
Thank you for this, Thomas. Yes there was a problem with it. A couple of copy/paste but not edit type of thing. It has been corrected. A new version of the tool will be posted sometime this weekend.
